services:
  - name: backend
    type: web
    plan: free
    dockerfilePath: backend/photo-map/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://<HOST>:<PORT>/<DATABASE_NAME>
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: sua_senha_forte

  - name: frontend
    type: web
    plan: free
    dockerfilePath: frontend/Dockerfile.prod
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://backend.onrender.com
