services:
  - name: backend
    type: web
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-cubrv...ahncs0-a:5432/photo_map_db
      - key: SPRING_DATASOURCE_USERNAME
        value: photo_map_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: olFXPrFw3jFnOVyLM74Tf2kNli4cIDZh

  - name: frontend
    type: web
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile.prod
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://backend.onrender.com
